version: '3.6'

services:
  app:
    image: node:19
    working_dir: /usr/app
    volumes:
      - ./app:/usr/app
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      bash -c "npm install && npm run build && npm run start"